layouts/partials/future.html
=> Add TBD events to left sidebar

layouts/index.html, layouts/partials/future.html
Better display of events that span months.
Fixes #71
=> Display month for events

layouts/partials/footer_scripts.html
=> Make javascript load async

gulpfile.js, package.json
Optimizes CSS inline automatically when merged/built to master.
Fixes #103
=> Add critical process#103

layouts/index.html, layouts/partials/footer_scripts.html, layouts/partials/map.html
=> Move map script to footer

gulp/tasks/process-html.js
=> Remove html min for speed

exampleSite/config.toml, layouts/partials/global_navbar.html
Includes example menu for spanish translation
Fixes #126 
=> Change menu to be driven from config.toml

layouts/_default/baseof.html
=> Disable sidebar on event pages

layouts/_default/baseof.html
=> Make sidebar not show up on events page

layouts/partials/future.html, layouts/partials/welcome.html
Fixes https://github.com/devopsdays/devopsdays-theme/issues/135
=> Display single-day events correctly

layouts/partials/global_navbar.html
Could probably use some tweaking, but at least it’s not squished
Fixes #177
=> Fix aspect ration on brain header

layouts/partials/event_navbar.html
This needs to be improved in #185 
Fixes #146 
=> Remove collapse from event level navbar

layouts/partials/head_includes.html
=> Add basic GA tracking

.travis.yml
Remove all the mocha and casper stuff because we don't use it anyway.
Also fix bad code for exluding node_modules from released zip file
=> Fix release stuff for travis

config.codekit3, gulp/tasks/default.js, gulp/tasks/process-html.js, netlify.toml
=> Re-add the gulp stuff for possible use in prod

layouts/talk/single.html
Fixes https://github.com/devopsdays/devopsdays-theme/issues/194
=> Adding clickable speaker image to talk page.

layouts/index.html, layouts/partials/future.html, layouts/partials/map.html, layouts/partials/past.html
Fixes https://github.com/devopsdays/devopsdays-theme/issues/203
Compare:
And:
=> Day two problems - fixed

exampleSite/data/events/2016-berlin.yml, exampleSite/data/events/2017-amsterdam.yml, exampleSite/data/events/2017-atlanta.yml, exampleSite/data/events/2017-austin.yml, exampleSite/data/events/2017-baltimore.yml, exampleSite/data/events/2017-beijing.yml, exampleSite/data/events/2017-charlotte.yml, exampleSite/data/events/2017-chicago.yml, exampleSite/data/events/2017-dallas.yml, exampleSite/data/events/2017-denver.yml, exampleSite/data/events/2017-detroit.yml, exampleSite/data/events/2017-hartford.yml, exampleSite/data/events/2017-indianapolis.yml, exampleSite/data/events/2017-los-angeles.yml, exampleSite/data/events/2017-minneapolis.yml, exampleSite/data/events/2017-moscow.yml, exampleSite/data/events/2017-ohio.yml, exampleSite/data/events/2017-paris.yml, exampleSite/data/events/2017-portland.yml, exampleSite/data/events/2017-salt-lake-city.yml, exampleSite/data/events/2017-sao-paulo.yml, exampleSite/data/events/2017-seattle.yml, exampleSite/data/events/2017-stockholm.yml, exampleSite/data/events/2017-tokyo.yml, exampleSite/data/events/2017-toronto.yml, exampleSite/data/events/2017-vancouver.yml, exampleSite/data/events/2017-washington-dc.yml, exampleSite/data/events/2017-zurich.yml, exampleSite/data/sponsors/netapp.yml
Bringing over current data files for dev environment.
=> Syncing up data files

layouts/index.html, layouts/partials/global_navbar.html, layouts/speaker/single.html, layouts/speakers/single.html, layouts/talk/single.html
=> Add alt tags to all images

layouts/speaker/single.html
Still not great, but this will look better after #57
Fixes #193
=> Change divs on speaker page to make image not so bad

layouts/partials/events/event_metadata.html
=> Make schema metadata only show on events with a startdate

layouts/_default/baseof.html
~This should likely never be merged; it's just to test what shows up on production.~
Turns out, I actually did fix a thing :)
=> Add debug for event page

.travis.yml
=> Change travis to container-based

exampleSite/config.toml, layouts/partials/events/event_metadata.html, layouts/partials/head/seo/open_graph.html
=> Correct some issues with open graph and schema

exampleSite/content/page/speaking.md
Perhaps my comment in https://github.com/devopsdays/devopsdays-theme/issues/180 is wrong and we definitely need to exclude this.
=> This page needs to be excluded from updates.

appveyor.yml, config.codekit3, exampleSite/config.toml, layouts/_default/baseof.html, layouts/event/single.html, layouts/events/single.html, layouts/partials/event_navbar.html, layouts/partials/events/cta.html, layouts/partials/events/event_metadata.html, layouts/partials/footer_scripts.html, layouts/partials/sponsors.html, layouts/partials/welcome.html, layouts/program/single.html, layouts/shortcodes/cfp_dates.html, layouts/shortcodes/email_organizers.html, layouts/shortcodes/email_proposals.html, layouts/shortcodes/event_end.html, layouts/shortcodes/event_link.html, layouts/shortcodes/event_location.html, layouts/shortcodes/event_logo.html, layouts/shortcodes/event_map.html, layouts/shortcodes/event_start.html, layouts/shortcodes/event_twitter.html, layouts/shortcodes/list_organizers.html, layouts/shortcodes/program_entry.html, layouts/speaker/single.html, layouts/speakers/single.html, layouts/talk/single.html, layouts/welcome/single.html
This fixes the spelling of the key, and also makes it slightly forward-compatible, so we can update it in devopsdays-web early.
Fixes #253
=> Fix spelling of path separator key

exampleSite/content/events/2017-ponyville/index.md, layouts/partials/head/seo/open_graph.html, layouts/partials/head/seo/schema.html
=> Update social graph tags for sub-pages

layouts/partials/head/seo/open_graph.html, layouts/partials/head/seo/schema.html
=> Add events path to event sharing image

config.codekit3, layouts/shortcodes/list_organizers.html
Fixes an issue with IE 11
Fixes #300
=> Change to not use flex on organizer page

contributing.json
=> Remove commit validation from contributing.json

layouts/shortcodes/list_organizers.html
This will attempt to make the organizer images resize properly.
=> Fix responsive issue on contacts page

layouts/partials/map.html
I'm happy to do some more work on the map. Maybe I'll make the labels a little nicer looking next. I did a lot of this a few years back, so this was a fast fix. I'm no web js expert, though. This might be a horrible solution idiomatically.
Fixes #316
=> Fix markers not being clickable

contributing.json
Fixes https://github.com/devopsdays/devopsdays-theme/issues/324
=> JFC, annoy me less; lowercase is fine, dammit

exampleSite/data/events/2017-ponyville.yml, gulp/tasks/responsive-images.js
Something got missed in a merge somewhere...
=> Check merge of organizer images

exampleSite/data/events/2017-ponyville.yml, exampleSite/utilities/README.md, gulp/tasks/responsive-images.js
This specifies the sizes recommended for the various images.
=> Update images guidelines

exampleSite/utilities/README.md
Added links to existing AI, PSD and SVG graphics as well as existing prospectuses
=> Added links to existing assets

exampleSite/config.toml, gulp/tasks/copy-static-files.js
=> Copy proper static files

exampleSite/utilities/README.md
=> fixed readme typo

exampleSite/data/events/2017-ponyville.yml
This updates Ponyville to take place in March now, so that we can see it before going live.
=> Update Ponyville dates

layouts/partials/sponsors.html
=> Fix sponsorship CTA for maxed out levels

exampleSite/data/events/2017-ponyville.yml, layouts/partials/events/cta.html
=> Make Propose and Register CTA buttons date-driven

.travis.yml, config.codekit3, utils/.gitignore, utils/dod-release.sh, utils/release-theme.sh, utils/update-content.sh
Fixes devopsdays/devopsdays-web#1846
Fixes #416
=> Add utils for managing releases and updates

layouts/events/single.html, layouts/index.html, layouts/partials/about.html, layouts/partials/events/cta.html, layouts/partials/footer.html, layouts/partials/future.html, layouts/partials/map.html, layouts/partials/past.html, layouts/partials/speaking.html, layouts/partials/sponsors.html, layouts/section/events.rss.xml, layouts/section/speaking.rss.xml
This takes care of the problem in #420
=> Fix now func in RSS

layouts/speakers/single.html
Fixes #426 
See https://github.com/devopsdays/devopsdays-web/pull/2104 for more details
=> Add check for legacy speaker files

layouts/partials/head/seo.html, layouts/partials/head/seo/twitter_cards.html
=> Add support for Twitter cards for social sharing

layouts/partials/head/seo/twitter_cards.html
=> Fix incorrect twitter card content

layouts/partials/head/seo/twitter_cards.html
=> Syntax error

utils/dod-release.sh
=> Let's use ssh

bin/netlify-production.sh, bin/netlify.sh
This changes the two netlify build scripts to use the build variables from netlify.
=> Change netlify scripts to use variables

config.codekit3, layouts/partials/footer.html
=> Make footer CFP only show actual open CFP

layouts/events/single.html, layouts/partials/future.html
Similar to 7108ce1f69a2f6b57f92e3b42a3696e4714e3da2
Fixes #424
=> Improve readability of events sidebar

layouts/_default/baseof.html
Fixes https://github.com/devopsdays/devopsdays-theme/issues/468
=> Removing broken link

config.codekit3, layouts/shortcodes/event_location.html
=> Remove extra space from location shortcode

layouts/index.html
Fixes https://github.com/devopsdays/devopsdays-theme/issues/481
=> Handle single-day events; only show needed months

bin/netlify-production.sh, bin/netlify.sh, netlify.toml
Fixes #494 
(well, sorta. we need to make a manual change to the netlify scripts on devopsdays-web too)
=> Update hugo version to 0.20.7

config.codekit3, layouts/speakers/single.html
=> Remove dodgy bio trimming code

bin/netlify-production.sh, bin/netlify.sh
This will use the embedded binary of hugo 0.20.7
=> use binary for hugo

layouts/talk/single.html
Work around #508 using Hugo. 
Fixes #508
=> Embed speakerdeck using hugo

bin/netlify.sh, netlify.toml
=> Bump hugo to 0.20.7

gulp/tasks/copy-css.js, gulp/tasks/copy-js.js, gulp/tasks/default.js, gulp/tasks/process-html.js, gulp/tasks/responsive-images.js
=> Remove fingerprinting step

config.codekit3, exampleSite/config.toml, layouts/partials/events/event_metadata.html, layouts/partials/footer_scripts.html, layouts/partials/head.html, layouts/partials/head/seo/open_graph.html, layouts/partials/head/seo/schema.html, layouts/partials/head/seo/twitter_cards.html, layouts/partials/head_includes.html, layouts/section/blog.rss.xml, layouts/section/events.rss.xml, layouts/section/speaking.rss.xml
=> Deprecate weburl

exampleSite/content/events/2017-ponyville/speakers/fluttershy.md, layouts/speakers/single.html
=> Make read more clickable ellipsis on speaker page

layouts/shortcodes/list_core.html
Moving @littleidea back to active.
=> ACS moving back to active

layouts/partials/sponsors.html
=> Make sponsor title singular if max is 1

config.codekit3, layouts/talk/single.html
=> Change to use embedly for speakerdeck

REFERENCE.md
This adds the details about the various pages and their frontmatter.
=> Add frontmatter information to reference file

layouts/speakers/single.html
Fixes #548. See justification /screenshots in issue.
=> Declutter speakers page

layouts/talk/single.html
Fixes https://github.com/devopsdays/devopsdays-theme/issues/551
=> Make twitter handle visible on talk pages too

exampleSite/content/events/2017-ponyville/program.md, layouts/program/single.html
=> Display content of program file on program page

REFERENCE.md, archetypes/blog.md, exampleSite/content/blog/2016-chicago.md, exampleSite/content/blog/2016-kansas_city.md, gulp/tasks/responsive-images.js, layouts/partials/head/seo/open_graph.html, layouts/partials/head/seo/schema.html, layouts/partials/head/seo/twitter_cards.html
=> Add sharing image to frontmatter for blog posts

layouts/section/events.rss.xml, layouts/section/speaking.rss.xml
=> Fix bad printf statement in feed generators

layouts/section/events.rss.xml
=> Add flavor text for title in event feed

layouts/speaker/single.html
=> Change verbiage on speaker page to not be talk-specific

netlify.toml
There is a new GH org, which might change things)
=> Try to update to hugo 0.23

package.json
Upgrading node module `run-sequence` to latest per greenkeeper.
=> Upgrade run-sequence

gulp/tasks/process-html.js, gulp/tasks/responsive-images.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/576)
=> Use only 1 and 2x enlargement

gulp/tasks/copy-static-files.js
=> Fix copy of old files

layouts/shortcodes/list_organizers.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/588)
=> Add Gitlab to organisers profile

config.codekit3, exampleSite/content/events/2017-ponyville/registration.md, exampleSite/data/events/2017-ponyville.yml, layouts/shortcodes/registration_end.html, layouts/shortcodes/registration_start.html
Fixes #592
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/593)
=> Add shortcodes for registration dates

exampleSite/content/events/2018-portland/program/aaron-aldrich-ignite.md, exampleSite/content/events/2018-portland/program/aaron-aldrich.md, exampleSite/content/events/2018-portland/program/heidi-waterhouse-ignite.md, exampleSite/content/events/2018-portland/program/jennifer-davis.md, exampleSite/content/events/2018-portland/program/tbd.md, exampleSite/content/events/2018-portland/speakers/aaron-aldrich.md, exampleSite/content/events/2018-portland/speakers/heidi-waterhouse.md, exampleSite/content/events/2018-portland/speakers/jennifer-davis.md, exampleSite/content/events/2018-portland/speakers/julia-wester.md, exampleSite/content/events/2018-portland/speakers/patrick-obrien.md, exampleSite/content/events/2018-portland/welcome.md, exampleSite/data/events/2018-portland.yml
updating data for portland
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/659)
=> Portland data update

layouts/index.html
Fixes https://github.com/devopsdays/devopsdays-web/pull/5398#issuecomment-421134971
cc @bridgetkromhout 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/661)
=> fix display of single-day events on home page

netlify.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/671)
=> Update hugo to 0.50

layouts/partials/future.html
Fixes #676
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/677)
=> displays single-day events correctly in front page sidebar

layouts/shortcodes/list_organizers.html
Fixes #678
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/679)
=> Make organizer cards the same height in a row

layouts/shortcodes/emoji.html
I have a speaker who'd like to use emoji in their bio. This turns out to be pretty easy to implement; yay!
Ref: https://gohugohq.com/partials/emojis-shortcode-for-hugo/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/687)
=> Adding emoji support
