devopsdays/devopsdays-theme

- layouts/partials/welcome.html
The styling is not great yet, but it’s there.
This also takes away the whole “try to find the logo and then put itthere if it’s there” nonsense.
Fixes #75
> Add content from welcome page to welcome partial

- exampleSite/data/events/2017-hoofington.yml
- exampleSite/data/events/2017-ponyville.yml
- layouts/partials/sponsors.html
- static/css/site.css
- static/site.less
> Tweak the sponsor margins

- layouts/partials/welcome.html
We were referencing the city name incorrectly to get it to show up in this header.
Also, changing the grammar per https://github.com/devopsdays/devopsdays-theme/issues/61 to better work when we transition to using event groups.
> Restoring missing city; changing grammar.

- exampleSite/content/events/2017-ponyville/speakers.md
- gulpfile.js
- layouts/partials/head.html
- layouts/partials/head/seo.html
- layouts/partials/head/seo/google_news.html
- layouts/partials/head/seo/open_graph.html
- layouts/partials/head/seo/schema.html
- layouts/partials/head/seo/twitter_cards.html
> Add basic social metadata

- archetypes/blog.md
- exampleSite/content/blog/2016-chicago.md
- layouts/blog/summary.html
- layouts/partials/footer.html
The proper metadata is also in the archtype for blog now.
Fixes #54
> Add support for Description to blog posts

- exampleSite/content/page/events.md
- layouts/_default/baseof.html
- layouts/events/single.html
- layouts/partials/future.html
- layouts/partials/past.html
* Adding the `/events` page much as it was before, only using the much-improved new `future` partial.
* Occam's Razor says our shortest path to a "/past" page is instead just linking the "/events" page.
* Slight fix to layout to prevent the next month's name from being immediately below the previous set of dates:
Before:
After:
> Event page

- exampleSite/data/events/2017-ponyville.yml
- layouts/partials/events/cta.html
- layouts/partials/welcome.html
> Add dynamic CTA buttons on welcome pages

- exampleSite/content/events/2017-minneapolis/welcome.md
- exampleSite/data/events/2017-minneapolis.yml
- layouts/event/single.html
- layouts/index.html
- layouts/partials/event_navbar.html
- layouts/partials/sponsors.html
- layouts/partials/welcome.html
Mostly cosmetic. A few layout changes @mattstratton will want to eyeball. Compare:
Before:
After:
> Event updates

- layouts/partials/events/event_metadata.html
- layouts/partials/footer_scripts.html
Description cannot be set because we cannot control bad characters
> Add structured metadata to events

- exampleSite/config.toml
- layouts/partials/head/seo/open_graph.html
Could still use twitter cards, but this is fine for now.
Fixes #128
> Add social graph headers

- layouts/talk/single.html
I tested this with Nicole Forsgren in 2016 MSP
Fixes #4 
> Make old-style talks compatible

- layouts/_default/baseof.html
Although "past events" appears another place in this file, that condition doesn't seem to be hit on the main page, and this one does.
Fixes https://github.com/devopsdays/devopsdays-theme/issues/142
> Moving past events to bottom of column

- layouts/shortcodes/event_twitter.html
Related to https://github.com/devopsdays/devopsdays-theme/issues/132 - this means that instead of using whatever param is set, the event_twitter shortcode will use what's in the datafile.
> Changing event twitter to use data file

- gulp/tasks/copy-static-files.js
The netlify redirects file was not being copied over, which is a problem.
> Add redirects to gulp task

- layouts/speakers/single.html
This change will allow events using the old-style (datafiles) to still have their speakers show up in /speakers on their event.
It is recommended that after this theme is deployed, any in-flight events migrate to the page-style method, but for now, this works.
Fixes #313
> Make speaker page backwards-compatible

- exampleSite/data/events/2017-ponyville.yml
- layouts/partials/events/event_navbar.html
~This is for https://github.com/devopsdays/devopsdays-web/issues/1819 although it won't entirely fix it (I've noted a bug that came to light).~ Update: https://github.com/devopsdays/devopsdays-web/issues/1829 now means that this...
Fixes https://github.com/devopsdays/devopsdays-web/issues/1819
Instead of putting this in every datafile, I'm setting the most common default menu options we create to have customized default icons. Moscow is a good example of having them all visible with the default, although ignore the extraneous plus sign for now - that's the extra welcome link bug:
I used the lightbulb for `propose` because otherwise anything mic-like I used would be too close to the `speakers` one. I know we used to use that lightbulb for the organizing page, but afaict we aren't using the …
> Set default icons for common event menu options

- layouts/shortcodes/list_organizers.html
> Make organizer image alt tags have the person’s name

- layouts/partials/sponsors.html
This allows for events to put in a specific URL for their sponsor, for event-level tracking.
Fixes #398 
> Add support for overriding sponsor URL at event level

- layouts/partials/events/event_navbar.html
If an event has set `registration_link` or `cfp_link`, there is no longer a need to set the URL’s on the nav elements.
Fixes #406
> Registration and Propose menus items use optional data fields

- config.codekit3
- exampleSite/data/events/2017-chicago.yml
- layouts/partials/google_analytics.html
- layouts/partials/head_includes.html
This allows the use of specifying a `ga_tracking_id` field in the datafile which will send the pageviews of just that particular event to that GA tracking location.
Fixes #414
> Add support for event-specific google analytics

- layouts/events/single.html
- layouts/index.html
- layouts/partials/about.html
- layouts/partials/events/cta.html
- layouts/partials/footer.html
- layouts/partials/future.html
- layouts/partials/map.html
- layouts/partials/past.html
- layouts/partials/speaking.html
- layouts/partials/sponsors.html
- layouts/section/events.rss.xml
- layouts/section/speaking.rss.xml
For some odd reason the deprecation message still appears when I run Hugo. I'll dig into this more, so please don't close #407 until I've investigated further.
The site builds and QA's fine with these changes.
> Removing usage of $.Now.Format in partials

- layouts/speakers/single.html
Reverts devopsdays/devopsdays-theme#427
Unfortunately, this fix led to 2016's speaker pages being displayed as empty:
To prevent this revert from re-introducing its previous problems, I'm removing unused speaker.md pages in https://github.com/devopsdays/devopsdays-web/pull/2126 and preventing them from being created too early in https://github.com/devopsdays/devopsdays-web/pull/2125.
> Revert "Add check for legacy speaker files"

- layouts/partials/events/event_metadata.html
Now it only displays structured metadata if there is an address set.
Fixes #445
> Fix event metadata

- layouts/partials/past.html
Fixes #444 
I tested this by setting Oslo and Chicago to have the same dates, and they disappeared. Applying this change restored them.
> Fix disappearing duplicate event dates in past

- layouts/shortcodes/event_twitter.html
Fixes https://github.com/devopsdays/devopsdays-theme/issues/479
Turns this:
Into this:
> Restore event twitter for old style events

- gulp/tasks/copy-static-files.js
- gulp/tasks/responsive-images.js
Since all it's doing is copying the files, we can do that much faster. This should shave 2-3 minutes off the build.
> Remove retina on images that don’t need it

- layouts/talk/single.html
As reported in https://github.com/devopsdays/devopsdays-theme/issues/542 it appears we didn't have code in the talk page to handle displaying vimeo. I've copied the youtube code and modified it to work with vimeo. In local testing this makes vimeo show up correctly.
This will need to be merged and released before https://github.com/devopsdays/devopsdays-web/pull/2471 works correctly.
Fixes https://github.com/devopsdays/devopsdays-theme/issues/542
> Adding vimeo as an option

- layouts/talk/single.html
I noticed a broken image on the talk page when locally testing a speaker who doesn't have an image yet. 
The speaker page, on the other hand, was fine.
This is the cause:
```
Bridgets-MacBook-Air:devopsdays-theme bridget$ grep -r speaker-default.png *
layouts/talk/single.html:            <img src = "{{"img/speaker-default.png" | absURL }}" class="img-fluid"  alt="{{ $.Scratch.Get "speakername" }}"/><br />
Bridgets-MacBook-Air:devopsdays-theme bridget$ find . -name speaker-default.png -print
Bridgets-MacBook-Air:devopsdays-theme bridget$
```
Fixes #547
> Correcting default speaker image

- contributing.json
I trip on this rule from time to time, and I don't think it's providing much value. I'm fine with being overruled on this.
> Remove requirement of no trailing dot

- gulp/tasks/responsive-images.js
This removes the 100% resizing of "images remaining" and simply does a resize. I'm hoping this makes it run a little faster, since it doesn't have to do any thinking.
> Simplify retina 

- layouts/partials/head.html
Fixes #539 
With this change, if the "default" titles are used, it will prepend "devopsdays CITY YEAR" to the beginning. This will help with google search results, etc.
> Prepend event name and year as needed to titles

- layouts/partials/welcome.html
As noted by @mattstratton in https://github.com/devopsdays/devopsdays-theme/issues/568 we aren't only linking to past but also all other events including future ones. 
Fixes https://github.com/devopsdays/devopsdays-theme/issues/568
> Other events aren't always only past

- REFERENCE.md
- exampleSite/content/events/2017-ponyville/registration.md
- layouts/shortcodes/google_form.html
Fixes #230 
This adds a shortcode for embedding Google Forms, but maintaining the responsive layout on mobile.
> Add shortcode for google forms

- layouts/talk/single.html
Before:
After:
Fixes https://github.com/devopsdays/devopsdays-theme/issues/578
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/587)
> Adds newline to talk page for #578.

- layouts/program/single.html
Fixes https://github.com/devopsdays/devopsdays-theme/issues/583
I wanted to spend some time learning how the DOD website works. I was looking over the issues list and found this easy one, so I fixed it.
I'm not a massive fan of the blue text over the orange squares. Thoughts?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/589)
> Adds links to open spaces description in the program

- layouts/shortcodes/list_organizers.html
This is a little nitpicky, but both GitHub and Twitter are served on `https`.
Linking to the `http` version causes a redirect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/594)
> Prefer https for github and twitter

- layouts/partials/welcome.html
What this does: if event_group set and there are multiple years, this now shows the "other events" that have the same event group.
This fixes https://github.com/devopsdays/devopsdays-theme/issues/61 assuming that event_group is properly set.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/614)
> Add event_group

- REFERENCE.md
- layouts/speaker/single.html
- layouts/talk/single.html
This PR changes the display of speaker attributes to make them appear below the picture on the speaker page. It was discussed in https://github.com/devopsdays/devopsdays-theme/issues/612.
* Optionally, they can be configured to be more verbose (displaying link targets)
* Treats pronouns like all other attributes (with appropriate link to pronoun.is explainer site)
Before:
After (compact):
After (verbose):
This PR also shortens the length limit of speaker bios on a talk page to send those interested to a speaker's detail page. The problem I'm trying to solve here is that speaker bios can be of arbitrary length and some are very long.  I'm interested in what @mattstratton thinks of this. (I can also split this out if desired. Also! I was considering …
> adjust how speaker bios and attributes show up

- exampleSite/content/events/2017-ponyville/index.md
- exampleSite/data/events/2017-ponyville.yml
- layouts/shortcodes/event_link.html
I'd like to extend the event_link shortcode to optionally pull from the event data - so that I can pull `cfp_link` and `registration_link` from my data file and link to them.
This PR adds two new properties to the shortcode, while preserving existing behaviour:
`url-key` - specifies a key whose value will be bond to the `href` of the link
`text-key` - specifies a key whose value will be bound to the text node of the link
If both `url-key` and `page` are specified, `url-key` will be preferred. Similarly, `text-key` will be preferred over `text`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/617)
> Allow event_link to also pull event data

- static/scss/custom.scss
Such as "Cape Town"
I tested this by manually editing the minified CSS in the `devopsdays-web` and running that locally.
I wasn't sure how I could test compiling the SASS and and using the CSS from there.
I also don't know if this is the right solution for the problem.
Feel free to just close this if it's not right.
But it does solve the problem of wrapping cities:
**Before:**
**After:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/637)
> Ensure that city names don't wrap

- netlify.toml
Theme previews that we deploy via netlify should use the same version of Hugo as the devopsdays-web repo so that the previews will accurately reflect what will ultimately go to production. This PR may gate some fixes I'm working on for datetime handling.
ref https://github.com/devopsdays/devopsdays-web/commit/d23d2bee577943fc6c4d8f7a155e8a970f89af4b
cc @bridgetkromhout
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/640)
> bumps hugo version to match devopsdays-web site

- layouts/_default/baseof.html
- layouts/speaker/single.html
- layouts/talk/single.html
For https://github.com/devopsdays/devopsdays-theme/issues/643
Reduce the overall rendering time by ~75% via the following:
- cache the entirely-static footer partial
- eliminate looping over all talks in speaker page
- eliminate looping over all speakers in talk page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/644)
> improves template rendering performance

- layouts/events/single.html
- layouts/index.html
- layouts/partials/events/cta.html
- layouts/partials/future.html
- layouts/partials/map.html
- layouts/section/events.rss.xml
- layouts/section/speaking.rss.xml
Many existing template partials take the current time (build time), cast it to a string, and compares it with the times from the event data (ex. start/end times) which are also being re-cast to strings here (twice!).
In order to allow us to use timezones as part of our comparison and not have the formatting involved in comparisons, use the `time` template function and directly compare against `now` without typecasting.
ref https://gohugo.io/functions/time/
ref https://gohugo.io/functions/now/
This PR does the same thing for start/endtime and registration times as #641.
---
There are still a few places where we're casting to strings, like in `partials/future.html` but in these cases we're starting with a string from the scratch space. So in other words we although we could do:
```
{{- if …
```
> updates to use time comparisons for start/end dates

- layouts/program/single.html
This whitespace seems to be an error. See discussion here: https://github.com/devopsdays/devopsdays-web/pull/5300#discussion_r215024752
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/650)
> Remove extra whitespace

- layouts/speaker/single.html
The performance improvement in #644 to the speaker page implicitly (and incorrectly) assumes that a speaker will give a single talk per event. Rather than using `.GetPage` which can return only a single
page, we can change the original call to `.Site.Pages` and get the correct behavior with at least some of the performance improvement.
This could be further improved if the program YAML included the event name, or if Hugo supported a "contains" or "startswith" operator in the where function.
Fixes https://github.com/devopsdays/devopsdays-theme/issues/643#issuecomment-421098679
Replaces https://github.com/devopsdays/devopsdays-web/pull/5404
I've tested this locally with the content in the main site, using the specific page called out in the issue …
> ensures speaker's multiple talks in a single event display

- layouts/partials/welcome.html
This uses similar code to what we're now using on the front page (thanks to @tgross) to fix the dates displaying incorrectly on the welcome pages.
This fixes the comparison so that we're no longer comparing a date that now includes times and concluding that there are two different dates when there's really only one day being represented.
Fixes #663
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/664)
> Fix for #663 (dates displayed incorrectly)

- gulp/tasks/copy-static-files.js
This should fix #662 
>I noticed that https://www.devopsdays.org/events/2016-minneapolis/speakers/ had broken images. I looked into it, and it appears that we don't have images loading correctly in archived events that have been built for the live site. If I check locally, it still doesn't work because www.devopsdays.org is baked into the static files. If I look directly at the URL of a speaker image locally (not a link to it), it does still exist and redirect to where it lives in /static: http://localhost:1313/events/2016-minneapolis/speakers/aj-bowen.jpg
Looks like the gulp task which copied old images from /public/events/2016-minneapolis/speakers/ wasn't copying them across to /dist/events/2016/minneapolis/speakers/ causing the images to be broken.
I spun up an example of the 'fixed' …
> Images not resolving in early static events.

- layouts/partials/future.html
I'm hotfixing this problem related to https://github.com/devopsdays/devopsdays-theme/issues/656 on the live site (https://github.com/devopsdays/devopsdays-web/pull/6180), but also putting it in the theme repo with this PR.
Before fix, notice how NYC is still present on the evening of its first day, but it's already scrolled off the sidebar on the left:
After hotfix, it's back:
Thanks to @kmugrage for reminding me about this problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/devopsdays/devopsdays-theme/684)
> Hotfix for sidebar

- REFERENCE.md
- layouts/shortcodes/tito_widget.html
We're using tito now in London (https://ti.to/) and I thought it might be helpful to include a shortcode so others don't have to go through embedding the widget code directly into their registration pages.
I'm not the biggest fan on requesting external resources so I don't mind dropping the CSS and JS into the static files if needed. (Please let me know :+1: )
In order to use this you enter `{{< tito_widget event="devopsdays-london/2019" >}}` for example on your page. If you want to only show a particular ticket then you can do something like `{{< tito_widget event="devopsdays-london/2019" releases="fiaurhghf2k">}}`. Similarly if you wanted to apply a discount to the widget you can use the `discount-code="examplediscount" ` param.
---
This change is [<img …
> Feature: Add shortcode for tito
